### ISSUE TITLE
Inefficient storage layout for statically sized arrays

### ISSUE THREAD

**Issue by MrChico** [vyperlang/vyper#1731] opened 2019-11-15 17:04 UTC
It seems that vyper stores statically sized arrays with the same encoding as dynamically sized arrays: with `loc(a[i])    =   #(a) + i` (using the syntax of https://github.com/ethereum/vyper/issues/769).

But since statically sized arrays have a known size, they can just be put out in storage directly. Solidity already does this https://solidity.readthedocs.io/en/latest/miscellaneous.html#layout-of-state-variables-in-storage and it would be nice to have compatibility here

**Comment by fubuloubu** [comment] 2019-11-15 18:41
Duplicate of https://github.com/ethereum/vyper/issues/1556

**Comment by MrChico** [comment] 2019-11-15 19:21
@fubuloubu that issue seems to mostly deal with packing. This is about redundant hashing of storage locations

**Comment by fubuloubu** [comment] 2019-11-15 19:37
@mrchico, my bad I didnt read that correctly.

**Comment by jacqueswww** [comment] 2019-11-22 23:37
Hmm the one risk with just using slots directly is that it makes slot attacks easier, i.e. if somehow we can bypass the check on `i` in a[i]; one could manipulate other (non-array and non-map) global variables - just a thought.

**Comment by fubuloubu** [comment] 2019-11-23 00:43
You would be encoding these state variables directly, using the indexing algorithm that compiler has (incrementing from zero). So, it shouldn't be possible to use it to interfere with other state variables (unless you're unlucky enough to have an array big enough that it interferes with with a hashed-type indexed variable like a mapping) because you could always calculate the next index as `loc(a) + len(a)`.

**Comment by iamdefinitelyahuman** [comment] 2021-07-19 19:55
fixed in #2361

**Closed by iamdefinitelyahuman** 2021-07-19 19:55 UTC
Labels: enhancement
