### ISSUE TITLE
Disable overflow/underflow protection by explicit declaration

### ISSUE THREAD

**Issue by vsmelov** [vyperlang/vyper#2335] opened 2021-03-22 14:59 UTC
## Simple Summary
As far as I understood the overflow/underflow protection is embedded in Vyper and always works.
I want to have a mechanism to explicit disable the protection for proved safe operations.

## Motivation
e.g.
```
while i < 10:
    i += 1
    # do something
```

```
if x > y:
    x = x - y
```

in these cases "safemath" protection will consume extra gas.

## Specification
I would make it with something like
```
with math_engine.disable_safemath:
    i += 1
```

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment] 2021-03-22 15:35
This would live better inside an optimization:
1. Where does the variable start? Is it limited or unlimited? (e.g. is `i = 0` to start)
2. Does the operation preclude overflows because of some prior assumption? (your `while i < 10` and `if x > y` conditions provide this)
3. Is it impossible, due to prior assumptions, that an overflow could happen?

We'd like to avoid more complex reconfiguration of internal safety logic, even if it might be intended behavior, and instead rely on the ability of an optimization pass (in this case, using the AST as a guide to remove unnecessary SafeMath operations) to carefully make any updates required.

**Comment by charles-cooper** [comment] 2022-03-22 17:36
should be resolved with the addition of explicit unsafe arithmetic functions in https://github.com/vyperlang/vyper/pull/2629

**Closed by charles-cooper** 2022-03-22 17:36 UTC
