### ISSUE TITLE
Unclear ambiguous type error

### ISSUE THREAD

**Issue by banteg** [vyperlang/vyper#2130] opened 2020-08-19 10:15 UTC
### Version Information

* vyper Version (output of `vyper --version`): 0.2.4+commit.7949850
* OS: linux
* Python Version (output of `python --version`): Python 3.7.3

### What's your issue about?

Unclear ambiguous type error on a simple code.

```python
# @version 0.2.4
from vyper.interfaces import ERC20

coins: constant(address[4]) = [
    0x6B175474E89094C44Da98b954EedeAC495271d0F,
    0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,
    0xdAC17F958D2ee523a2206206994597C13D831ec7,
    0x0000000000085d4780B73119b644AE5ecd22b376,
]

@external
def recycle():
    balances: uint256[4] = empty(uint256[4])
    for i in range(4):
        balances[i] = ERC20(coins[i]).balanceOf(msg.sender)
```

```
StructureException: Ambiguous type
  contract "contracts/Recycle.vy", function "recycle", line 31:28
       30     for i in range(4):
  ---> 31         balances[i] = ERC20(coins[i]).balanceOf(msg.sender)
  ------------------------------------^
```

### How can it be fixed?

You tell me

**Comment by iamdefinitelyahuman** [comment] 2020-08-19 10:17
Looks like constant folding is the issue...  `coins[i]` ends up changed to `[0x6B175474E89094C44Da98b954EedeAC495271d0F, 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, 0xdAC17F958D2ee523a2206206994597C13D831ec7, 0x0000000000085d4780B73119b644AE5ecd22b376][i]` and the type checker gets confused if it's looking at an `address[4]` or a `Bytes[20][4]`.

I see two issues to address here:

1. We need to properly differentiate between address and bytes types when folding.
2. The "Ambiguous type" error should explain which types it's seeing, so that the problem is easier to diagnose.

**Comment by charles-cooper** [comment] 2021-07-27 22:03
I think a dup of https://github.com/vyperlang/vyper/issues/2156

**Comment by charles-cooper** [comment] 2021-07-27 22:04
The ambiguous type error looks like it's been fixed, now it's
```
$ vyper -f ir repros/2130.vy 
Error compiling: repros/2130.vy
vyper.exceptions.StructureException: Looking for a variable location, instead got a value
  contract "repros/2130.vy", function "recycle", line 14:28 
       13     for i in range(4):
  ---> 14         balances[i] = ERC20(coins[i]).balanceOf(msg.sender)
  ------------------------------------^
       15

```

**Comment by charles-cooper** [comment] 2022-01-06 01:31
this was fixed in https://github.com/vyperlang/vyper/pull/2580

**Closed by charles-cooper** 2022-01-06 01:31 UTC
Labels: bug
