### ISSUE TITLE
vyper.exceptions.UnimplementedException: <exception str() failed>

### ISSUE THREAD

**Issue by AntonD3** [vyperlang/vyper#3049] opened 2022-08-08 16:25 UTC
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3
* OS: macOS
* Python Version (output of `python --version`): 2.7.16

### What's your issue about?
```
vyper-0.3.3 error: vyper.exceptions.UnimplementedException: <exception str() failed>
[14238] Failed to execute script 'vyper_compile' due to unhandled exception!
```
```
@external
@pure
def main() -> uint64:
    sum: uint64 = 0
    for i in range(2147483637, 2147483647):
        sum += 1
    return sum

```

**Comment by charles-cooper** [comment] 2022-08-10 16:42
duplicate of https://github.com/vyperlang/vyper/issues/2840

**Closed by charles-cooper** 2022-08-10 16:42 UTC
