### ISSUE TITLE
Unable to declare array of dynamic bytes 

### ISSUE THREAD

**Issue by AntonD3** [vyperlang/vyper#3043] opened 2022-08-08 15:45 UTC
### Version Information

* vyper Version (output of `vyper --version`): 0.3.3

### What's your issue about?

```
vyper-0.3.3 error: vyper.exceptions.StructureException: Multidimensional Bytes arrays are not supported
  contract "tests/vyper/external/abiEncoderV2/calldata_array_dynamic_index_access.vy", function "k", line 3:9 
       2 @pure
  ---> 3 def k(s: Bytes[100][2], which: uint256) -> bool:
  ----------------^
       4     return True

[13502] Failed to execute script 'vyper_compile' due to unhandled exception!
```

```
vyper-0.3.3 error: vyper.exceptions.StructureException: Bytes arrays are not supported
  contract "tests/vyper/external/abiEncoderV2/calldata_array_multi_dynamic.vy", function "j", line 3:9 
       2 @pure
  ---> 3 def j(s: DynArray[Bytes[10], 5]) -> bool:
  ----------------^
       4     return True

[13565] Failed to execute script 'vyper_compile' due to unhandled exception!
```

Source codes:
```
@external
@pure
def k(s: Bytes[100][2], which: uint256) -> bool:
    return True

```

```
@external
@pure
def j(s: DynArray[Bytes[10], 5]) -> bool:
    return True

```

Is it a normal behavior?

**Comment by charles-cooper** [comment] 2022-08-09 14:41
the former is blocked; the latter is not (as of v0.3.4)

**Comment by charles-cooper** [comment] 2022-08-10 16:40
duplicate of https://github.com/vyperlang/vyper/issues/2762

**Closed by charles-cooper** 2022-08-10 16:40 UTC
