### ISSUE TITLE
bug: IR labels for different functions can collide

### ISSUE THREAD

**Issue by tserg** [vyperlang/vyper#3448] opened 2023-05-23 13:51 UTC
### Version Information

* vyper Version (output of `vyper --version`): https://github.com/vyperlang/vyper/commit/95bf73f493dc8458a1d6981493275379197a4bdf
* OS: linux
* Python Version (output of `python --version`): 3.10.8

### What's your issue about?

The generation of labels for `goto` statements can result in the same labels for different functions. IR generation succeeds but assembly generation will fail.

```
struct A:
    a :uint256

struct _A:
    a: uint256

@external
@view
def f(b:_A) -> uint256:
    return 1

@external
def f_(b:A):
    pass
```

h/t @trocher @ptrcarta

### How can it be fixed?

Fill this in if you know how to fix it.

**Comment by charles-cooper** [comment] 2023-05-30 16:54
Confirmed, closing as duplicate of #3226

**Closed by charles-cooper** 2023-05-30 16:54 UTC
Labels: bug - codegen, bug - type 0
