### ISSUE TITLE
Cannot post events after create an uninitialized local variable

### ISSUE THREAD

**Issue by JustinDrake** [vyperlang/vyper#1476] opened 2019-06-11 14:35 UTC
When working with the Eth2 deposit contract I noticed a strange behaviour which I presume is a compiler bug.

Notice that the tests pass in https://github.com/ethereum/eth2.0-specs/pull/1152/commits/abe48cc98857c3350d45656d3d4a6f2e6af2784d (the command to run the tests is `make compile_deposit_contract; make test_deposit_contract`) but fail if you move [line 92](https://github.com/ethereum/eth2.0-specs/blob/abe48cc98857c3350d45656d3d4a6f2e6af2784d/deposit_contract/contracts/validator_registration.v.py#L92) (the `Deposit` log) to line 80 the tests fail when nothing has really changed. I haven't had time to debug it but my guess would be that that it has something to do with `zero_bytes32: bytes32`, possibly that junk is being written to it.

**Comment by fubuloubu** [comment] 2019-06-11 15:21
To prove that theory, could you move line 92 to just before line 80, and modify line 80 to be `zero_bytes21: bytes32 = 0x0000....0000`, and see if you get the same issue?

It does indeed seem strange to be encountering this behavior

**Comment by JustinDrake** [comment] 2019-06-11 15:31
What's the syntax again? I tried `zero_bytes32: bytes32 = 0x00`, `zero_bytes32: bytes32 = 0`, `zero_bytes32: bytes32 = bytes32(0)`—all fail.

**Comment by fubuloubu** [comment] 2019-06-11 16:24
You either have to type out all the zeros, use `convert(0, bytes32)`, or simply use `EMPTY_BYTES32`. All should work.

**Comment by JustinDrake** [comment] 2019-06-11 18:02
Yep, when explicitly setting `zero_bytes32: bytes32 = convert(0, bytes32)` it works. Definitely compiler bug.

**Comment by fubuloubu** [comment] 2019-06-11 23:46
Not sure why this creates exceptional behavior, but I agree it definitely shouldn't be doing that.

**Comment by davesque** [comment] 2019-06-12 19:50
@JustinDrake 

I'm having trouble reproducing this failure.  I checked out https://github.com/ethereum/eth2.0-specs/commit/abe48cc98857c3350d45656d3d4a6f2e6af2784d , moved line 92 to be line 80 (put it just before the uninitialized `zero_bytes32` variable declaration), and the functional tests are passing for me:
<img width="740" alt="Screen Shot 2019-06-12 at 1 47 38 PM" src="https://user-images.githubusercontent.com/791437/59381551-d55ec480-8d18-11e9-8df2-5acfcc14a319.png">

The failure is because the ABIs don't match due to the gas estimates being different.  That in itself is weird and I'm trying to understand what's going on there, but is that related to the issues you were having?  My guess is not.

**Comment by davesque** [comment] 2019-06-12 19:51
@JustinDrake Do you have a link to a failing build job or something that would make it a bit clearer how things are failing for you?

**Comment by JustinDrake** [comment] 2019-06-12 20:07
@davesque Can you also show the output of `make compile_deposit_contract` (which should be run before `make test_deposit_contract`).

**Comment by davesque** [comment] 2019-06-13 20:40
Alright, here's what I'm getting.  And I'm guessing this is the error you're seeing:
```
(venv) Davids-MacBook-Pro-2 ~/projects/eth2.0-specs
$ make compile_deposit_contract
Makefile:101: warning: overriding commands for target `eth2.0-spec-tests/tests'
Makefile:98: warning: ignoring old commands for target `eth2.0-spec-tests/tests'
cd ./deposit_contract; . venv/bin/activate; \
        python tool/compile_deposit_contract.py contracts/validator_registration.v.py;
(venv) Davids-MacBook-Pro-2 ~/projects/eth2.0-specs
$ make test_deposit_contract
Makefile:101: warning: overriding commands for target `eth2.0-spec-tests/tests'
Makefile:98: warning: ignoring old commands for target `eth2.0-spec-tests/tests'
cd ./deposit_contract; . venv/bin/activate; \
        python -m pytest .
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.6.8, pytest-3.6.1, py-1.8.0, pluggy-0.6.0
rootdir: /Users/david/projects/eth2.0-specs/deposit_contract, inifile:
collected 11 items

tests/contracts/test_compile.py .                                                                                                                                                                                                      [  9%]
tests/contracts/test_deposit.py .........F                                                                                                                                                                                             [100%]

================================================================================================================== FAILURES ==================================================================================================================
_____________________________________________________________________________________________________________ test_deposit_tree ______________________________________________________________________________________________________________

registration_contract = <web3._utils.datatypes.Contract object at 0x10885e6d8>, w3 = <web3.main.Web3 object at 0x10880f9e8>, assert_tx_failed = <function assert_tx_failed.<locals>.assert_tx_failed at 0x10870cbf8>
deposit_input = (b'\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x1...""""""""""""""""', b'333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333')

    def test_deposit_tree(registration_contract, w3, assert_tx_failed, deposit_input):
        log_filter = registration_contract.events.Deposit.createFilter(
            fromBlock='latest',
        )

        deposit_amount_list = [randint(MIN_DEPOSIT_AMOUNT, FULL_DEPOSIT_AMOUNT * 2) for _ in range(10)]
        leaf_nodes = []
        for i in range(0, 10):
            tx_hash = registration_contract.functions.deposit(
                *deposit_input,
            ).transact({"value": deposit_amount_list[i] * eth_utils.denoms.gwei})
            receipt = w3.eth.getTransactionReceipt(tx_hash)
            print("deposit transaction consumes %d gas" % receipt['gasUsed'])

            logs = log_filter.get_new_entries()
            assert len(logs) == 1
            log = logs[0]['args']

            assert log["index"] == i.to_bytes(8, 'little')

            deposit_data = DepositData(
                pubkey=deposit_input[0],
                withdrawal_credentials=deposit_input[1],
                amount=deposit_amount_list[i],
                signature=deposit_input[2],
            )
            hash_tree_root_result = hash_tree_root(deposit_data)
            leaf_nodes.append(hash_tree_root_result)
            root = compute_merkle_root(leaf_nodes)
>           assert root == registration_contract.functions.get_deposit_root().call()
E           AssertionError: assert b'f\xa3=\x90\...4\xb6\xe6\x10' == b'n\xaa\xe6\x8...f-Zz\x14\xd2+'
E             At index 0 diff: 102 != 110
E             Use -v to get the full diff

tests/contracts/test_deposit.py:163: AssertionError
------------------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------------------
deposit transaction consumes 122642 gas
==================================================================================================== 1 failed, 10 passed in 20.15 seconds ====================================================================================================
make: *** [test_deposit_contract] Error 1
(venv) Davids-MacBook-Pro-2 ~/projects/eth2.0-specs
$
```

**Comment by JustinDrake** [comment] 2019-06-13 20:46
Yep, that's the error! :) (Note that the error changes every time because there is some randomisation.)

**Comment by davesque** [comment] 2019-06-13 20:58
@JustinDrake Yeah, I did notice that.  Thanks for the help.

**Comment by charles-cooper** [comment] 2019-06-18 01:48
@JustinDrake does https://github.com/ethereum/vyper/pull/1484 fix the issue for you?

**Comment by charles-cooper** [comment] 2019-06-19 15:51
but also, uninitialized variables are not guaranteed to refer to zeroed memory. so maybe we should disallow declaring variables without initializing them.

**Comment by fubuloubu** [comment] 2019-06-19 19:38
> so maybe we should disallow declaring variables without initializing them.

:+1: this

**Comment by charles-cooper** [comment] 2019-06-19 20:11
Or always set new variables to 0. I'm open to either TBH - let's discuss at next meeting?

**Comment by fubuloubu** [comment] 2019-06-19 20:12
Agreed, but forcing the user to set is more explicit and clear and avoids this condition entirely.

Could optimize out the write if it is probable that no read occurs before write.

**Comment by rajeevgopalakrishna** [comment] 2019-06-25 04:54
So uninitialised variables are not guaranteed for now to have default initial values as the documentation seems to suggest here: https://vyper.readthedocs.io/en/latest/types.html#initial-values?

**Comment by fubuloubu** [comment] 2019-06-25 06:16
Yeah, it seems that was an oversight.

**Comment by jacqueswww** [comment] 2019-06-25 18:00
@charles-cooper this feels like a bug, when is memory not zeroed/initialised ?

**Comment by charles-cooper** [comment] 2019-06-25 18:51
I think after a call to a private function as you suspected in https://github.com/ethereum/vyper/issues/1493#issuecomment-505556220. There could be something else going on but I inspected the IR and didn't see set to 0 for new variables that are declared after return from private.

**Comment by jacqueswww** [comment] 2019-06-25 19:06
Yip we should fix that, for Basetypes it should be relatively easy. Dynamic types will be slightly more work, as we need zero the whole range.

**Comment by fubuloubu** [comment] 2019-06-25 19:10
It doesn't seem like this is the right answer then. Shouldn't whatever solution we come up with avoid the need to set dynamic types, which will be needlessly expensive?

**Comment by jacqueswww** [comment] 2019-06-25 19:17
It's quite of an edge case that I don't think it should be too much of a problem, defining karge dynamic types in the EVM will always be costly.

**Comment by davesque** [comment] 2019-06-25 21:11
@jacqueswww I'm trying to remember if the zero by default behavior applies to the EVM memory in addition to the storage.  If that were the case, wouldn't uninitialized variables already be zeroed assuming the memory counter is incremented to accommodate them?  I'm poking through the spec right now trying to see if this is the case.  I'm also a bit out of context here so feel free to correct me.

**Comment by davesque** [comment] 2019-06-25 21:16
Actually, yeah here's where I saw that in the "Execution Model" section of the yellow paper: 
<img width="494" alt="Screen Shot 2019-06-25 at 3 12 35 PM" src="https://user-images.githubusercontent.com/791437/60134175-29779900-975c-11e9-8aa5-ef7116bc1f5d.png">

**Comment by davesque** [comment] 2019-06-25 21:20
Are memory positions re-used across the execution of a method call?  If so, then I can understand the trouble.

**Comment by jacqueswww** [comment] 2019-06-25 21:26
@davesque Yes that is true, but this occurs after a local call was made - which re uses the same memory.

**Comment by jacqueswww** [comment] 2019-06-25 21:46
@davesque just looking at the exception above further,

```
@public
@constant
def get_deposit_root() -> bytes32:
    node: bytes32 = 0x0000000000000000000000000000000000000000000000000000000000000000
    size: uint256 = self.deposit_count
    for height in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if bitwise_and(size, 1) == 1:  # More gas efficient than `size % 2 == 1`
            node = sha256(concat(self.branch[height], node))
        else:
            node = sha256(concat(node, self.zero_hashes[height]))
        size /= 2
    return node
```
This is the function that fails?

**Comment by davesque** [comment] 2019-06-26 18:13
@jacqueswww Yeah, it's a bit confusing to reproduce.  I made a fork with a commit that shows the failure.  Here's how you can access it:
```bash
git clone https://github.com/davesque/eth2.0-specs/
cd eth2.0-specs
git checkout with-failure
make install_deposit_contract_test
make compile_deposit_contract
make test_deposit_contract
```
The `with-failure` tag is on a commit that makes the change that produces the failure.  The `without-failure` tag is the commit just before that which doesn't produce the failure.

**Comment by davesque** [comment] 2019-06-26 18:13
@jacqueswww Here's the actual commit that causes the failure: https://github.com/davesque/eth2.0-specs/commit/1c2858f9068a228845617e9965d812adb5235680

**Comment by davesque** [comment] 2019-07-01 21:10
I think many of the people involved in this discussion are already aware of this, but for posterity here's a comment I just posted with more information about what I think is happening here: https://github.com/ethereum/vyper/issues/1493#issuecomment-507424856

**Comment by charles-cooper** [comment] 2019-07-01 21:16
There might be something else going on here too because I'm not sure the frame of the private function in this issue is that large to overwrite callee memory. But I did notice that the newly declared variable is not zeroed in the IR as I mentioned above, and the fact that explicitly setting the new variable fixes the issue is pretty telling.

**Comment by charles-cooper** [comment] 2021-08-04 14:34
Should be fixed in https://github.com/vyperlang/vyper/pull/2403/commits/be42f18f4950159d2d2a534d3539c6b1e5ba4c44. The issue was that the buffer for the encoded data was allocated AFTER the code to call the internal functions was evaluated. So the code to save the current call frame knows nothing about the encoded buffer, and then the internal function is free to clobber the buffer.

**Closed** 2021-08-06 01:50 UTC
Labels: bug
