### ISSUE TITLE
The @constant attribute allows state-modifying instructions

### ISSUE THREAD

**Issue by axic** [vyperlang/vyper#1932] opened 2020-04-22 00:56 UTC
The following compiles:
```
@public
@constant
def hash() -> bytes32:
    return sha256("hash")
```

This should not compile, because the `sha256` precompile uses `CALL`. Perhaps the compiler believes it is not state modifying, but technically `CALL` is. This could be fixed by #1929.

However the problem is if any other contract depends on `hash()` being "constant" and executes it via `STATICCALL`, then they will face a failure, because it is not possible to execute `CALL` within a `STATICCALL` frame. Even Vyper supposedly [calls `@constant` using `STATICCALL`](https://vyper.readthedocs.io/en/latest/structure-of-a-contract.html?highlight=staticcall#defining-interfaces-and-making-external-calls).

Found with @MrChico.

**Comment by fubuloubu** [comment] 2020-04-22 03:08
The `@constant` decorator currently just adjusts the ABI for the given function, but we do perform an AST check for mutation violations:
https://github.com/vyperlang/vyper/blob/ee8c18dbd228887c91af185872df15aa750e4f4f/vyper/exceptions.py#L157

This issue is therefore a duplicate of #1929. We could add a bytecode-level verification as a secondary check. It would have caught this issue earlier, and ensures that deployed code will operate exactly as intended.

**Comment by axic** [comment] 2020-04-22 10:33
Sorry it seems to be my mistake. [EIP-214](https://eips.ethereum.org/EIPS/eip-214) (defining `STATICCALL`) has an exception for `CALL` with zero-value (forgotten about this obscure part):
> Any attempts to make state-changing operations inside an execution instance with STATIC set to true will instead throw an exception. These operations include CREATE, CREATE2, LOG0, LOG1, LOG2, LOG3, LOG4, SSTORE, and SELFDESTRUCT. They also include CALL with a non-zero value.

So technically Vyper was correct, because the precompiles are called with zero-value. Still #1929 will make it nicer.

**Comment by fubuloubu** [comment] 2020-04-22 14:43
Closing in favor of resolution in #1929

**Closed by fubuloubu** 2020-04-22 14:43 UTC
Labels: Easy Pickings, bug
