### ISSUE TITLE
 Deploying vyper contract with brownie throws InvalidType 

### ISSUE THREAD

**Issue by Doc-Pixel** [vyperlang/vyper#2955] opened 2022-07-06 18:02 UTC
### Environment information

* `brownie` Version: 1.19.1
* `ganache-cli` Version: 
* `solc` Version: 7.0.4
* Python Version: 3.8.10
* OS: linux (ubuntu 20.*)
* Vyper: 0.3.4+commit.ac8cb6e6

### What was wrong?
When trying to deploy a vyper contract using brownie, it throws an error

Commit 3cbdf35bfd0e416eb8235a63b20921e4dc9cf293 introduced this behaviour
**I walked through vyper commits and pinpointed the behavior to commit 3cbdf35bfd0e416eb8235a63b20921e4dc9cf293
The previous commit df2da6202bda1909f4f2c13fe6e1f07bcb172b9f runs test successful**
```
ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ brownie run deploy1155.py
Brownie v1.19.0 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.4
Unhandled exception in 'contracts/ERC1155ownable.vy':
InvalidType: Subscript must be a literal integer
  contract "contracts/ERC1155ownable.vy", line 35:16 
       34 # the contracts URI to find the metadata
  ---> 35 baseuri: String[MAX_URI_LENGTH]
  ------------------------^
       36 contractURI: public(String[MAX_URI_LENGTH])
```
MAX_URI_LENGTH is an uint256 with value 300
```# URI length set to 300. 
MAX_URI_LENGTH: constant(uint256) = 300 
```

When compiling directly with Vyper, the compilation is successful.
```
ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ vyper ./contracts/ERC1155ownable.vy -f combined_json
{"contracts/ERC1155ownable.vy": {"bytecode": "0x602061281e600039600051600001608060208261281e0160003960005
```

### How can it be fixed?
I don't know

**Comment by Doc-Pixel** [comment] 2022-07-06 18:02
I walked through vyper commits and pinpointed the behavior to commit 3cbdf35bfd0e416eb8235a63b20921e4dc9cf293
The previous commit df2da6202bda1909f4f2c13fe6e1f07bcb172b9f runs test successful

Below the whole process.

Big question: Is this a vyper or a brownie issue?
Vyper compiles OK from the CLI (bottom of code snip)

```
ethbox@ethbox-VirtualBox:~/Vyper-Main/mySecretProject-contract$ pip install git+https://github.com/vyperlang/vyper.git@df2da6202bda1909f4f2c13fe6e1f07bcb172b9f --force-reinstall
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/vyperlang/vyper.git@df2da6202bda1909f4f2c13fe6e1f07bcb172b9f
  Cloning https://github.com/vyperlang/vyper.git (to revision df2da6202bda1909f4f2c13fe6e1f07bcb172b9f) to /tmp/pip-req-build-1zu339an

...................

ethbox@ethbox-VirtualBox:~/Vyper-Main/mySecretProject-contract$ vyper --version
0.3.4+commit.df2da620
ethbox@ethbox-VirtualBox:~/Vyper-Main/mySecretProject-contract$ brownie test
Brownie v1.19.0 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.4
Generating build data...
 - mySecretProject

========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.5, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/ethbox/Vyper-Main/mySecretProject-contract
plugins: eth-brownie-1.19.0, web3-5.29.1, xdist-1.34.0, hypothesis-6.27.3, forked-1.4.0
collected 16 items                                                                                                                                                                                                                      

Launching 'ganache-cli --chain.vmErrorsOnRPCResponse true --wallet.totalAccounts 10 --hardfork istanbul --miner.blockGasLimit 12000000 --wallet.mnemonic brownie --server.port 8545'...

tests/test_mySecretProject.py ................                                                                                                                                                                                           [100%]

========================================================================================================== 16 passed in 8.08s ===========================================================================================================
Terminating local RPC client...
ethbox@ethbox-VirtualBox:~/Vyper-Main/mySecretProject-contract$ pip install git+https://github.com/vyperlang/vyper.git@3cbdf35bfd0e416eb8235a63b20921e4dc9cf293 --force-reinstall
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/vyperlang/vyper.git@3cbdf35bfd0e416eb8235a63b20921e4dc9cf293
  Cloning https://github.com/vyperlang/vyper.git (to revision 3cbdf35bfd0e416eb8235a63b20921e4dc9cf293) to /tmp/pip-req-build-bg30h1ai

...................

ethbox@ethbox-VirtualBox:~/Vyper-Main/mySecretProject-contract$ brownie test
Brownie v1.19.0 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.4
Unhandled exception in 'contracts/mySecretProject.vy':
InvalidType: Subscript must be a literal integer
  contract "contracts/mySecretProject.vy", line 47:9 
       46 # the contracts URI to find the metadata
  ---> 47 baseuri: String[MAX_URI_LENGTH]
  -----------------^
       48 contractURI: public(String[MAX_URI_LENGTH])


ERROR: Unable to load project

ethbox@ethbox-VirtualBox:~/Vyper-Main/metawarp-contract$ vyper ./contracts/metaWarp.vy 
0x60206140e260003960005160806020826140e201600039600051116140dd576020816140e201600039600051806040526020820181816140e201606039505050602061410260003960005160106020826140e201600039600051116140dd576020816140e2016000396000518060e052602082016020816140e20160003960005161010052505050602061412260003960005161012c6020826140e201600039600051116140dd576020816140e20160003960005180610120526020820181816140e20161014039505050602061414260003960005161012c6020826140e201600039600051116140dd576020816140e20160003960005180610280526020820181816140e2016102a039505050604051806019556000602082601f0104600481116140dd57801561014557905b602081026060015181601a015560010181811861012d575b50505060e05180601e5561010051601f55503360015561012051806003556000602082601f0104600a81116140dd57801561019557905b602081026101400151816004015560010181811861017c575b5050506102805180600e556000602082601f0104600a81116140dd5780156101d257905b602081026102a0015181600f01556001018181186101b9575b505050613eee6101ee
```

**Comment by tserg** [comment] 2022-07-07 02:08
Running `vyper CONTRACT.vy -f ast` throws the same error.

This is because user-defined constants are not folded yet when generating the AST after  https://github.com/vyperlang/vyper/commit/3cbdf35bfd0e416eb8235a63b20921e4dc9cf293, causing semantics typechecking to fail because a literal value cannot be derived for the length of a dynamic array.

I think #2832 will resolve this.

**Comment by charles-cooper** [comment] 2022-07-10 13:56
@Doc-Pixel should be fixed as of #2958 - can you check again?

**Comment by Doc-Pixel** [comment] 2022-07-10 17:07
Updated vyper from the repo, tested again

```
ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ brownie --version
Brownie v1.19.0 - Python development framework for Ethereum

ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ vyper --version
0.3.4+commit.6c363614
ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ brownie test
Brownie v1.19.0 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.4
Generating build data...
 - ERC1155ownable
  File "/usr/local/lib/python3.10/dist-packages/brownie/test/plugin.py", line 87, in pytest_load_initial_conftests
    active_project = project.load(project_path)
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/main.py", line 768, in load
    return Project(name, project_path)
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/main.py", line 188, in __init__
    self.load()
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/main.py", line 245, in load
    self._compile(changed, self._compiler_config, False)
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/main.py", line 100, in _compile
    build_json = compiler.compile_and_format(
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/compiler/__init__.py", line 142, in compile_and_format
    build_json.update(generate_build_json(input_json, output_json, compiler_data, silent))
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/compiler/__init__.py", line 328, in generate_build_json
    build_json[contract_alias] = vyper._get_unique_build_json(
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/compiler/vyper.py", line 255, in _get_unique_build_json
    pc_map, statement_map, branch_map = _generate_coverage_data(
  File "/usr/local/lib/python3.10/dist-packages/brownie/project/compiler/vyper.py", line 314, in _generate_coverage_data
    source = source_map.popleft()
IndexError: pop from an empty deque

ERROR: Unable to load project

ethbox@ethbox-VirtualBox:~/Vyper-Main/ERC1155$ 
```

**Comment by Doc-Pixel** [comment] 2022-07-10 17:08
I tested with 2 projects that have not changed since I ran into this issue.

**Comment by tserg** [comment] 2022-07-11 04:27
I have traced it to https://github.com/vyperlang/vyper/commit/8d869952786f6c0694ec870c8f3b2e67ad24444e. I think we need Brownie to account for this vyper signature in the bytecode.

**Comment by charles-cooper** [comment] 2022-07-13 14:56
@Doc-Pixel should be fixed as of https://github.com/eth-brownie/brownie/commit/9745b3261b462a3dc78452e559556f520f7fdf8f, can you please close if the issue is resolved?

**Comment by Doc-Pixel** [comment] 2022-07-14 03:00
Installed the mentioned commit and the very latest vyper, tested and it works!

**Closed** 2022-07-14 03:00 UTC

**Comment by liam-ot** [comment] 2022-07-30 17:13
error message:
```
$ brownie compile
Brownie v1.19.0 - Python development framework for Ethereum

Compiling contracts...
  Vyper version: 0.3.4
Generating build data...
 - nft
  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/compile.py", line 50, in main
    proj = project.load()
  File "brownie/project/main.py", line 768, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 188, in __init__
    self.load()
  File "brownie/project/main.py", line 245, in load
    self._compile(changed, self._compiler_config, False)
  File "brownie/project/main.py", line 100, in _compile
    build_json = compiler.compile_and_format(
  File "brownie/project/compiler/__init__.py", line 142, in compile_and_format
    build_json.update(generate_build_json(input_json, output_json, compiler_data, silent))
  File "brownie/project/compiler/__init__.py", line 328, in generate_build_json
    build_json[contract_alias] = vyper._get_unique_build_json(
  File "brownie/project/compiler/vyper.py", line 255, in _get_unique_build_json
    pc_map, statement_map, branch_map = _generate_coverage_data(
  File "brownie/project/compiler/vyper.py", line 314, in _generate_coverage_data
    source = source_map.popleft()
IndexError: pop from an empty deque
```

vyper version:
```
$ vyper --version
0.3.4+commit.f31f0ec
```

getting the same issue when trying to compile using the latest version of vyper

**Comment by sqx0597** [comment] 2022-08-10 04:22
> error message:
> 
> ```
> $ brownie compile
> Brownie v1.19.0 - Python development framework for Ethereum
> 
> Compiling contracts...
>   Vyper version: 0.3.4
> Generating build data...
>  - nft
>   File "brownie/_cli/__main__.py", line 64, in main
>     importlib.import_module(f"brownie._cli.{cmd}").main()
>   File "brownie/_cli/compile.py", line 50, in main
>     proj = project.load()
>   File "brownie/project/main.py", line 768, in load
>     return Project(name, project_path)
>   File "brownie/project/main.py", line 188, in __init__
>     self.load()
>   File "brownie/project/main.py", line 245, in load
>     self._compile(changed, self._compiler_config, False)
>   File "brownie/project/main.py", line 100, in _compile
>     build_json = compiler.compile_and_format(
>   File "brownie/project/compiler/__init__.py", line 142, in compile_and_format
>     build_json.update(generate_build_json(input_json, output_json, compiler_data, silent))
>   File "brownie/project/compiler/__init__.py", line 328, in generate_build_json
>     build_json[contract_alias] = vyper._get_unique_build_json(
>   File "brownie/project/compiler/vyper.py", line 255, in _get_unique_build_json
>     pc_map, statement_map, branch_map = _generate_coverage_data(
>   File "brownie/project/compiler/vyper.py", line 314, in _generate_coverage_data
>     source = source_map.popleft()
> IndexError: pop from an empty deque
> ```
> 
> vyper version:
> 
> ```
> $ vyper --version
> 0.3.4+commit.f31f0ec
> ```
> 
> getting the same issue when trying to compile using the latest version of vyper

I encountered the same problem. I tried to update the version of brownie and solved it
